package com.leyou.game.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig friendDaoConfig;
    private final DaoConfig crowdDaoConfig;
    private final DaoConfig searchHistoryDaoConfig;

    private final FriendDao friendDao;
    private final CrowdDao crowdDao;
    private final SearchHistoryDao searchHistoryDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        friendDaoConfig = daoConfigMap.get(FriendDao.class).clone();
        friendDaoConfig.initIdentityScope(type);
        searchHistoryDaoConfig = daoConfigMap.get(SearchHistoryDao.class).clone();
        searchHistoryDaoConfig.initIdentityScope(type);
        crowdDaoConfig = daoConfigMap.get(CrowdDao.class).clone();
        crowdDaoConfig.initIdentityScope(type);

        friendDao = new FriendDao(friendDaoConfig, this);
        crowdDao = new CrowdDao(crowdDaoConfig, this);
        searchHistoryDao = new SearchHistoryDao(searchHistoryDaoConfig, this);
        registerDao(SearchHistory.class, searchHistoryDao);
        registerDao(Friend.class, friendDao);
        registerDao(Crowd.class, crowdDao);
    }

    public void clear() {
        friendDaoConfig.getIdentityScope().clear();
        crowdDaoConfig.getIdentityScope().clear();
        searchHistoryDaoConfig.getIdentityScope().clear();
    }

    public FriendDao getFriendDao() {
        return friendDao;
    }

    public CrowdDao getCrowdDao() {
        return crowdDao;
    }

    public SearchHistoryDao getSearchHistoryDao() {
        return searchHistoryDao;
    }

}
