package com.leyou.game.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

/**
 * Entity mapped to table "PHONE_CONTACT".
 */
public class PhoneContact implements Parcelable {

    private Long id;
    public static final int NO_SYSTEM = 1;//未注册用户 显示邀请好友
    public static final int SYSTEM_NO_FRIEND = 2;//已注册 平台内非好友
    public static final int ADDING_WAITING_CONFIRM = 4;//已发送添加好友请求 显示 等待验证
    public static final int ADDING_FRIEND_REFUSED = 5;//是否通过验证 显示 已拒绝
    public static final int ADDING_FRIEND_PASS_VERIFY = 6;//是否通过验证 显示 通过验证
    public Integer status;
    public String userId;
    public String name;
    public String headImgUrl;
    public String nickname;
    public String phoneNameLetter;
    /** Not-null value. */
    private String phone;

    public PhoneContact() {
    }

    public PhoneContact(Long id) {
        this.id = id;
    }

    public PhoneContact(Integer status, String userId, String headImgUrl,String name, String nickname, String phone) {
        this.status = status;
        this.userId = userId;
        this.name = name;
        this.headImgUrl = headImgUrl;
        this.nickname = nickname;
        this.phone = phone;
    }
    public PhoneContact(Long id, Integer status, String userId, String headImgUrl,String name, String nickname, String phoneNameLetter, String phone) {
        this.id = id;
        this.status = status;
        this.userId = userId;
        this.name = name;
        this.headImgUrl = headImgUrl;
        this.nickname = nickname;
        this.phoneNameLetter = phoneNameLetter;
        this.phone = phone;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public Integer getStatus() {
        return status;
    }

    public void setStatus(Integer status) {
        this.status = status;
    }

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhoneNameLetter() {
        return phoneNameLetter;
    }

    public void setPhoneNameLetter(String phoneNameLetter) {
        this.phoneNameLetter = phoneNameLetter;
    }

    /** Not-null value. */
    public String getPhone() {
        return phone;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getHeadImgUrl() {
        return headImgUrl;
    }

    public void setHeadImgUrl(String headImgUrl) {
        this.headImgUrl = headImgUrl;
    }

    public String getNickname() {
        return nickname;
    }

    public void setNickname(String nickname) {
        this.nickname = nickname;
    }

    @Override
    public String toString() {
        return "PhoneContact{" +
                "id=" + id +
                ", status=" + status +
                ", userId='" + userId + '\'' +
                ", name='" + name + '\'' +
                ", headImgUrl='" + headImgUrl + '\'' +
                ", nickname='" + nickname + '\'' +
                ", phoneNameLetter='" + phoneNameLetter + '\'' +
                ", phone='" + phone + '\'' +
                '}';
    }

    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeValue(this.id);
        dest.writeValue(this.status);
        dest.writeString(this.userId);
        dest.writeString(this.name);
        dest.writeString(this.headImgUrl);
        dest.writeString(this.nickname);
        dest.writeString(this.phoneNameLetter);
        dest.writeString(this.phone);
    }

    protected PhoneContact(Parcel in) {
        this.id = (Long) in.readValue(Long.class.getClassLoader());
        this.status = (Integer) in.readValue(Integer.class.getClassLoader());
        this.userId = in.readString();
        this.name = in.readString();
        this.headImgUrl = in.readString();
        this.nickname = in.readString();
        this.phoneNameLetter = in.readString();
        this.phone = in.readString();
    }

    public static final Parcelable.Creator<PhoneContact> CREATOR = new Parcelable.Creator<PhoneContact>() {
        @Override
        public PhoneContact createFromParcel(Parcel source) {
            return new PhoneContact(source);
        }

        @Override
        public PhoneContact[] newArray(int size) {
            return new PhoneContact[size];
        }
    };
}
